composed removed []
Rightpoint/BonMot pull request #426
Opened 2023-01-15 04:31 UTC by DevVenusK

[] can be removed when using the composed method.
Overloading methods for optional use.

2023-01-15 13:54 UTC, ZevEisenberg commented
@DevVenusK thanks for your contribution! I don't fully understand the issue that this fixes. Would you mind posting a reproduction case? For bonus points, and unit test would be great as well.

2023-01-16 12:07 UTC, DevVenusK commented
Currently we have to use it like this to use the compose method.
`.composed(of: [ 
"apple".styled(...),
"is delicious".styled(...)
])`

However, if you use the added method, you can do this.
`.composed(of: 
"apple".styled(...),
"is delicious".styled(...)
)`

I really like the missing [].

2023-01-16 14:57 UTC, ZevEisenberg commented
Ah, now I understand. Can you perhaps simplify the code by calling through to an existing function, passing along the array from the variadic parameters, instead of duplicating the whole function body?

2023-01-17 00:35 UTC, DevVenusK commented
good idea! I fixed it!
Would you mind posting a description?

2023-01-17 01:57 UTC, ZevEisenberg commented
A description of what?

2023-01-17 02:37 UTC, DevVenusK commented
Sorry, I meant documentation comments, not a description. Is it okay to use the documentation comments of this method as is?

2023-01-17 06:14 UTC, ZevEisenberg requested changes
If the comment is copy-and-pasted, it should be good, with the exception of any mention of an array, which should probably be changed to "list"

2023-01-17 06:14 UTC, ZevEisenberg commented on Sources/Composable.swift
> +    /// - parameter composables: An array of `Composable` to join into an
Not an array any more

2023-01-17 06:44 UTC, DevVenusK commented
Oh, I hadn't thought of that thanks. Edited.

2023-01-17 21:39 UTC, ZevEisenberg commented
Looking good! I'd still like to see a unit test to make sure we don't break this syntax in future.

2023-01-25 13:23 UTC, DevVenusK commented
Write unit test for variadic parameter. 🙇🏻‍♂️

2023-01-25 16:05 UTC, ZevEisenberg requested changes

2023-01-25 16:05 UTC, ZevEisenberg commented on Tests/ComposableTests.swift
> +
Please remove extra whitespace

2023-01-25 16:05 UTC, ZevEisenberg commented
Nice test! Let's get the whitespace cleaned up and then we're good to merge.

2023-01-28 03:46 UTC, DevVenusK commented
> Nice test! Let's get the whitespace cleaned up and then we're good to merge.

done!

2023-01-28 04:48 UTC, ZevEisenberg approved these changes

2023-02-07 13:55 UTC, DevVenusK commented
@ZevEisenberg Do you have any idea when this PR will be merged?

2023-02-07 16:21 UTC, ZevEisenberg commented
Sorry, I've been procrastinating on it because I don't know if our CocoaPods release process works any more. I'll see what I can do.

2023-02-07 16:21 UTC, merged

2023-02-07 18:22 UTC, ZevEisenberg commented
Merged, but having trouble with the CocoaPods release, as anticipated. Working on it.

2023-02-08 00:41 UTC, DevVenusK commented
thx!! 🤩

2023-02-16 16:05 UTC, vpavelRP commented
@DevVenusK @ZevEisenberg THe cocoapods 6.1.2 is published as well